# bundle install
# bundle exec jekyll serve
# https://pages.github.com/versions/

# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# jekyll new --skip-bundle .

# aws s3 cp --recursive s3://myBucket/dir localdir
# aws s3 sync s3://mybucket/dir localdir

# https://github.com/jekyll/minima

title: Najaa Technologies Blog
email: hello@najaa.org
description: >- # this means to ignore newlines until "baseurl:"
    Blog about Technology, Software Development and Education.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.najaa.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: najaatech
github_username: najaatech
google_analytics: G-QVY6K7Q08L
show_excerpts: true
cdn_url: https://najaa-files.s3.me-south-1.amazonaws.com

# Build settings
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag

minima:
    skin: classic
    social_links:
        - { platform: github, user_url: "https://github.com/najaatech" }
        - { platform: twitter, user_url: "https://twitter.com/najaatech" }
        - { platform: youtube, user_url: "https://www.youtube.com/najaatech" }
        - { platform: linkedin, user_url: "https://www.linkedin.com/in/najaatech" }
        - { platform: instagram, user_url: "https://www.instagram.com/najaatech" }
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
